### ISSUE TITLE
weird characters in cli console

### ISSUE THREAD

**Issue by Jean757** [jpenilla/TabTPS#10]
When i use any tabtps command in cli server console i get weird unexcepted characters as you can see on the screenshot below

![screenshot](https://user-images.githubusercontent.com/63728252/109059401-84595480-76e4-11eb-88c4-8f77c78b4cee.png)

The minecraft server actually run paper-1.16.5-471 and a few plugins (discomc, SetHome, Worldedit and TabTPS)
The host server run Debian 10

**Comment by jpenilla** [comment]
Your paper is outdated, this is fixed in newer builds.
