### ISSUE TITLE
[Fabric] Incompatability with Java 8

### ISSUE THREAD

**Issue by NisargIO** [jpenilla/TabTPS#11]
**Describe the bug**
https://paste.gg/p/anonymous/d22b29d5893a49f9b23e49990217eaf9 (Without other Mods)
https://paste.gg/p/anonymous/ace8aa0347c442e484d04a4bd0dc7e57 (With Mods)

**To Reproduce**
1. Start the server

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: [1.16.5]

**Comment by jpenilla** [comment]
I am unable to reproduce. Can you provide some more information about the environment your server is running in? Operating System, JDK vendor/version, etc.

**Comment by NisargIO** [comment]
I am on Windows 10

java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Comment by jpenilla** [comment]
Hm, it seems like this is a Java 8 related issue. I am able to reproduce by using Java 8, but not using 11 or 15. For now I would recommend [updating to Java 11](https://adoptopenjdk.net/), however I will be looking into fixing this issue as the mod is built for Java 8+.

**Comment by NisargIO** [comment]
Yup that worked!

**Comment by jpenilla** [comment]
Fixed in https://github.com/jpenilla/TabTPS/commit/50dc3133a6aa48617e80140869240003dcbde070
