### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Decme** [jpenilla/TabTPS#12]
I'm testing this on a Fabric server 1.16.5

Server crashes on launch, log file shows this error:
> - Mod 'adventure-platform-fabric' (adventure-platform-fabric) recommends version 0.1 or later of mod colonel, which is missing!

Other mods:
Fabric API, Lithium, Simple-anti-xray, Spark, Starlight

Launch bat:

@echo off
echo Setting JAVA_HOME
set JAVA_HOME=C:\Program Files\Java\jdk-11.0.5
echo setting PATH
set PATH=C:\Program Files\Java\jdk-11.0.5\bin;%PATH%
echo Display java version
java -version
cls
echo This script will keep your server running even after crashing!
title Minecraft WatchDog
:StartServer
start /wait java -Xms3500M -Xmx3500M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -Xloggc:gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=128K -Dusing.aikars.flags=true -Daikars.new.flags=true -jar fabric-server-launch.jar nogui
echo (%time%) Server closed/crashed... restarting!
goto StartServer

**Comment by jpenilla** [comment]
The "error" you provided is simply a warning which can be ignored, it won't be present in future versions. For me to further diagnose this issue, I would need the crash logs.
Without the logs it's just a guess, but you may be having a similar issue to #11, in which case the [latest snapshot](https://jenkins.jpenilla.xyz/job/TabTPS/lastSuccessfulBuild/) may fix your issue.
Let me know if that build fixes your problem, and if not, please share the full logs.

**Comment by Decme** [comment]
The snapshot fixes it, thanks!
