### ISSUE TITLE
actionbar display not working on Paper 1.20.6

### ISSUE THREAD

**Issue by queenbiscuit311** [jpenilla/TabTPS#129]
**Describe the bug**
On Purpur 1.20.6, displaying information on the actionbar doesn't appear to work, even though it used to on 1.20.4. I haven't yet tested if this bug also shows up on regular paper or spigot.

In this screenshot, tabtps on actionbar, bossbar, and tab are all enabled, but only the latter two are showing up.

**To Reproduce**
1. Try to use tabtps on purpur 1.20.6
2. toggle information on actionbar to on
3. actionbar information missing

**Expected behavior**
Information should show up on the actionbar as it did on previous versions.

**Screenshots**
![image](https://github.com/jpenilla/TabTPS/assets/88851292/65579e56-1035-45cf-84f8-8f7f5d04c377)
In this screenshot, tabtps on actionbar, bossbar, and tab are all enabled, but only the latter two are showing up.

**Server Software and Version:**
 - Vendor: Purpur
 - Minecraft Version: 1.20.6
 - Output of /version command: 1.20.6-2211-3d25693 (MC: 1.20.6)

**Comment by jpenilla** [comment]
You need to use snapshot builds of TabTPS for 1.20.6 support currently.
