### ISSUE TITLE
Server instantly crashes with tabtps-fabric-mc1.16.5-1.3.4

### ISSUE THREAD

**Issue by Luracasmus** [jpenilla/TabTPS#14]
**Describe the bug**
Server instantly crashes with `tabtps-fabric-mc1.16.5-1.3.4`.

[latest.log](https://paste.gg/p/anonymous/3e2cdf0fc8e946779ce9ff771f0c2edd)

**To Reproduce**
1. Install `tabtps-fabric-mc1.16.5-1.3.4`
2. Start the server

**Expected behavior**
The server starts without crashing.

**Server Software and Version:**
 - Vendor: [Fabric]
 - Minecraft Version: [1.16.5]
 - Fabric Loader Version: [0.11.3]
 - Java: [AdoptOpenJDK jre-16.0.0.36-hotspot]

**Mods:**
- appleskin-mc1.16-fabric-1.0.11
- cloth-config-4.11.19-fabric
- crossstitch-0.1.2
- fabric-api-0.32.5+1.16
- FabricProxy-Lite-1.1.1
- InvView-1.4.1-1.16.4+
- krypton-0.1.2
- lazydfu-0.1.2
- lithium-fabric-mc1.16.5-0.6.4
- shulkerboxtooltip-2.3.5+1.16.5
- starlight-fabric-1.0.0-RC1-1.16.x
- tabtps-fabric-mc1.16.5-1.3.4
- vanish-1.16.4+-1.2.4
- worldedit-mod-7.2.4

**Additional context**
This doesn't happen with `tabtps-fabric-mc1.16.5-1.3.3`, only `tabtps-fabric-mc1.16.5-1.3.4` and later.

**Comment by jpenilla** [comment]
Thanks for the report :) This is actually an issue I've already fixed in the latest snapshot, I've just yet to make a new release yet. You can download it [here](https://jenkins.jpenilla.xyz/job/TabTPS/lastSuccessfulBuild/) for now.
