### ISSUE TITLE
[Feature Request] multi language support

### ISSUE THREAD

**Issue by KirilCrut** [jpenilla/TabTPS#15]
I think it would be nice to add support for different languages.

**Comment by jpenilla** [comment]
Per-user locales are already supported, however only English translations are included (as I only know English). Feel free to either drop your own locale files into the Jar, or to make a PR with more locales.

Here is a link to the default English file: https://github.com/jpenilla/TabTPS/blob/master/common/src/main/resources/tabtps_en_US.properties
