### ISSUE TITLE
The command 'tabtps toggle tab' isn't functioning on Paper-1.21.1-68-master with tabtps-spigot-1.3.25

### ISSUE THREAD

**Issue by TunArun** [jpenilla/TabTPS#178]
**Describe the bug**
I can only use `/tabtps help` on client and `tabtps:tps` `tabtps:mem` etc on server.
`tabtps toggle tab` is not exists
[log](https://paste.gg/p/anonymous/71af78490cd341f3907d6a3113ae6e54) 
[display-conf](https://paste.gg/p/TunArund/106ef20eb0bd40fa926ae5aea6714f27)

**To Reproduce**
run [start.sh](https://paste.gg/p/TunArund/1b472748e3724343b2b1e828a7007fb6) Paper-1.21.1-68 with tabtps-spigot-1.3.25 on Ubuntu 20.04 by owner of the directory
enter `tabtps toggle tab`

**Expected behavior**
Paper will tell you `[01:51:02 INFO]: Incorrect argument for command`

**Screenshots**
![image](https://github.com/user-attachments/assets/e9fc9b62-a74d-455f-be50-32505cc48840)
![image](https://github.com/user-attachments/assets/8d1591e7-df74-41c2-8248-9d2efed7fe8a)
![image](https://github.com/user-attachments/assets/3159b92a-4af2-46ba-8ecd-a647a6243669)

**Server Software and Version:**
 - Vendor: Leaves-1.21.1(Paper-1.21.1-68)
 - Minecraft Version: 1.21.1
 - Output of /version command: This server is running Leaves version 1.21.1-68-master@b33c46c (2024-10-12T05:25:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Comment by jpenilla** [comment]
Cannot reproduce with latest Paper 1.21.1, ensure your permissions are set properly and test with a vanilla client.
![image](https://github.com/user-attachments/assets/b52c9b79-027e-431d-8b37-edea7137dcea)
Toggle is a player-only command, console not being able to use it is normal. Currently it also won't with with `execute as <player> run <command>` from console, but that would be best addressed with a separate issue.
