### ISSUE TITLE
System CPU utilization shows as -100% when the actual value is not available

### ISSUE THREAD

**Issue by FarLanderCraft** [jpenilla/TabTPS#22]
**Describe the bug**
CPU -100% (Linux and/or Fabric issue?)
Happens regardless of other mods, even in a server on its own.
https://paste.ubuntu.com/p/SgCHyGR8rj/

**To Reproduce**
1. On Linux (I'm using Arch, specifically), start a Fabric server with TabTPS installed.
2. run `/tickinfo`

**Expected behavior**
Actual CPU utilization on sys. portion

**Screenshots**
![image](https://user-images.githubusercontent.com/67613281/126884650-d4bb2bd3-be7b-4b81-8a7c-5b2203de590a.png)

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.17.1
 - Output of /version command:
![image](https://user-images.githubusercontent.com/67613281/126884679-0acd0e67-7cc5-40c0-a477-067ce2f78a4d.png)

**Additional context**
I don't really know what else to add...

**Comment by jpenilla** [comment]
This basically means system usage is not available.

To quote [the Javadoc](https://docs.oracle.com/en/java/javase/15/docs/api/jdk.management/com/sun/management/OperatingSystemMXBean.html#getCpuLoad()) for the method I use to get system cpu usage: "If the recent cpu usage is not available, the method returns a negative value."

There isn't much I can do about this from the TabTPS side of things, however a possible improvement might be to not display system utilization when it's unavailable, instead of displaying invalid data.

I don't think the issue here is related to your operating system, as I test and develop the mod on Arch Linux as well.

**Comment by FarLanderCraft** [comment]
> This basically means system usage is not available.

> I don't think the issue here is related to your operating system, as I test and develop the mod on Arch Linux as well.

Why would it be unavailable? Could it be a problem with the server's JVM arguments?

```
java -jar -Xms1024M -Xmx3072M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true fabric-server-launch.jar nogui
```

**Comment by jpenilla** [comment]
It's more likely to be something with your system configuration, or with the JVM and how it interacts with your system. Are you running in a VM, or on bare metal?

I also noticed this commit to OpenJDK: https://github.com/AdoptOpenJDK/openjdk-jdk/commit/e2106d5af6244a9394be10106619ea5ac3262a9a

That commit is included in JDK 17, but not 16. It might be worth trying out one of the [early access 17 builds](https://jdk.java.net/17/) to see if anything changes there.

**Comment by FarLanderCraft** [comment]
> It's more likely to be something with your system configuration, or with the JVM and how it interacts with your system. Are you running in a VM, or on bare metal?
> 
> I also noticed this commit to OpenJDK: [AdoptOpenJDK/openjdk-jdk@e2106d5](https://github.com/AdoptOpenJDK/openjdk-jdk/commit/e2106d5af6244a9394be10106619ea5ac3262a9a)
> 
> That commit is included in JDK 17, but not 16. It might be worth trying out one of the [early access 17 builds](https://jdk.java.net/17/) to see if anything changes there.

Bare metal, on my main system. And I will try the Java 17 build now.

**Comment by FarLanderCraft** [comment]
![image](https://user-images.githubusercontent.com/67613281/126998742-949cb2be-a853-47ea-82e5-1320d0751834.png)
Java 17 is displaying it correctly, thank you. :D
(Out of sheer laziness I just hacked the conflicting mod so instead of depending on 
"Java": "16"
it depends on
"Java": "*"
(10/10 idea nothing can go wrong wait why is my game crashing ;-; )

**Comment by jpenilla** [comment]
Nice, I'm glad that worked. I'm going to close this issue as it seems resolved to me.
