### ISSUE TITLE
[Feature Request] Player Nicknames

### ISSUE THREAD

**Issue by Munchkinnibbler** [jpenilla/TabTPS#24]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be great if there was a feature to nickname yourself and other players and then have that appear on tab where the player's IGN would normally go. I know it's not exactly what tabtps was designed for but it would be a nice bit of customisation.

**Additional context**
It could be implemented as a command with something like /tabtps nickname usernamehere nicknamehere.

**Comment by jpenilla** [comment]
This is definitely out of scope for TabTPS.
