### ISSUE TITLE
[Feature Request] make it for forge

### ISSUE THREAD

**Issue by Techlord210** [jpenilla/TabTPS#34]
i want it for forge server pls can u make it
thanks

**Comment by z0z0r4** [comment]
I need too

**Comment by terminalmaid** [comment]
asking a fabric dev to port to forge is like asking a blacksmith to use a stone hammer instead of steel because "all the other tribes use stone hammers" "i cant use steel hammers" "the other blacksmiths say stone hammers are better"

**Comment by terminalmaid** [comment]
please close this issue, it's pointless

**Comment by averyterrel** [comment]
Close this issue and use Server Tab Info, which is for forge

**Comment by Techlord210** [comment]
> Close this issue and use Server Tab Info, which is for forge

Ok. LGTM
