### ISSUE TITLE
[1.18.2 Crash] Not compatible with Create Fabric

### ISSUE THREAD

**Issue by itsdinkd** [jpenilla/TabTPS#39]
[**Describe the bug**
Server crashes when a user places a Deployer by Create and corrupts chunk. Server will restart anytime player enters chunk. 

**To Reproduce**
1. Add Create Fabric
2. Add TabTPS
3. Place Deployer

**Expected behavior**
Crashes

**Server Software and Version:**
 - Vendor: [e.g. Paper, Purpur, Spigot, Tunity]: Fabric
 - Minecraft Version: [e.g. 1.15.2, 1.16.3]: 1.18.2

**Additional context**
https://github.com/Fabricators-of-Create/Create/issues/117
https://github.com/Fabricators-of-Create/Create/issues/314

**Comment by jpenilla** [comment]
Not really a TabTPS issue, this is an issue with Create's fake player implementation, see https://github.com/KyoriPowered/adventure-platform-fabric/issues/15, https://github.com/KyoriPowered/adventure-platform-fabric/issues/14, etc
