### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mocksonline** [jpenilla/TabTPS#49]
**Is your feature request related to a problem? Please describe.**
I think your TPS monitoring is very awesome, but tabtps conflicts with styledplayerlist([StyledPlayerList](https://github.com/Patbox/StyledPlayerList)), I'm frustrated. Can you add support for Text Placeholder API[TextPlaceholderAPI](https://github.com/Patbox/TextPlaceholderAPI)?

**Describe the solution you'd like**
Add support for Text Placeholder API[TextPlaceholderAPI](https://github.com/Patbox/TextPlaceholderAPI), such as %TabTPS:tps_60s%.

**Describe alternatives you've considered**
NULL

**Additional context**
NULL

**Comment by mocksonline** [comment]
Fabric version

**Comment by jpenilla** [comment]
I'm confused if this is reporting a mod conflict bug or requesting a feature. GitHub issues should each be for one topic, not multiple things thrown into one, please open proper issues with necessary details.
