### ISSUE TITLE
Create release for 1.19.4

### ISSUE THREAD

**Issue by louie-github** [jpenilla/TabTPS#58]
As the title suggests, the newest commit 139608470361b0d457722bdcaa10c02b3bd91f9c reads "Update dependencies for full 1.19.4 support", but no release has been posted yet.

The latest one is for 1.19.3. Is this mod ready for 1.19.4, or are there more things that need to be fixed before a jar file can be produced?

Thank you!

**Comment by AwesomeGenius** [comment]
we really need one, I can't use tabtps on my 1.19.4 fabric server in the meantime
