### ISSUE TITLE
"enable-on-login=true" not working

### ISSUE THREAD

**Issue by cbz1314** [jpenilla/TabTPS#71]
I set the "enable-on-login=true" but is not working for normal player, it only works on OP player
action-bar-settings {
    allow=true
    enable-on-login=true
    modules="cpu,tps,mspt,memory,ping"
    # The text used to separate modules. Accepts MiniMessage (i.e. " <gray>|</gray> ")
    separator=" "
    theme=default
}

**Server Software and Version:**
 - Vendor: paper
 - Minecraft Version: 1.20
 - Output of /version command: paper-1.20.1-100

**Additional context**

**Comment by jpenilla** [comment]
They must have permission for the display config you are using, from the default display config:
```hocon
# The permission required to use this display config
# Can be an empty string ("") to require no permission
permission="tabtps.defaultdisplay"
```
