### ISSUE TITLE
Lack of translations on Forgified Fabric (dynamic compatibility)

### ISSUE THREAD

**Issue by mpustovoi** [jpenilla/TabTPS#86]
**Describe the bug**
### (Please forgive me)
When using the mod with the **Forgified Fabric API** and **Sinytra Connector**, none of the label translations work. Technically, the mod still works fine (for example, the TPS and MSPT are displayed correctly).
Logs: https://gist.github.com/mpustovoi/334b2db03816f1d7c477e8c59735277b

**To Reproduce**
1. Install Forge 1.20.1
2. Install last versions of Forgified Fabric API and Sinytra Connector for Forge 1.20.1
3. Install TabTPS for Fabric 1.20.1
4. Execute either _/memory_, or _/tickinfo_, or _/tabtps toggle_ actionbar
5. See technical names of all labels and messages instead of their translations

**Expected behavior**
It was expected that the translations would work the same way as on Fabric, for example.

**Screenshots**
![image](https://github.com/jpenilla/TabTPS/assets/92390626/62ef4112-82b1-4e61-b5cf-b5586f087ac1)

**Server Software and Version:**
 - Vendor: Forge
 - Forgified Fabric API 0.90.7+1.10.2+1.20.1
 - Sinytra Connector 1.0.0-beta.25+1.20.1
 - TabTPS v.1.3.18 for Fabric 1.20.1
 - Minecraft Version: 1.20.1

**Additional context**
I tried to solve the problem through the resource pack, but the mod doesn't have _assets_, and putting the _xyz_ directory neither there nor in the root of the resource pack doesn't help.
(If we consider that all this dynamic transfer of Fabric to Forge is unpredictable and there is no simple way to fix it, I will understand)

**Comment by jpenilla** [comment]
Duplicate #65, TabTPS Fabric supports fabric-loader and fabric-api.
