### ISSUE TITLE
java.lang.IllegalStateException: Cannot remove non-existing user

### ISSUE THREAD

**Issue by daniel-skopek** [jpenilla/TabTPS#91]
**Describe the bug**
https://pastebin.com/raw/6QZqWKbB

**To Reproduce**
1. Join to the server
2. Sometimes the error will appear and player is kicked from a server

**Server Software and Version:**
 - Vendor: Pufferfish
 - Minecraft Version: 1.20.1
 - Output of /version command: This server is running Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)

**Comment by jpenilla** [comment]
It looks like you have another plugin (possibly ProtocolLib?) causing errors when the player joins, it disconnects them (firing quit event) when no join event ever happened. This is an invalid state that TabTPS doesn't expect.
