### ISSUE TITLE
[Feature Request] Fabric 1.20.3 support

### ISSUE THREAD

**Issue by Themis3000** [jpenilla/TabTPS#93]
Currently the latest published version does not work in 1.20.3, it would be cool to see it updated to work with the latest version!

I appreciate your work on this project, no rush! 1.20.3 was just released today. Thought I'd just open an issue so I can track on it & get it back on my server as soon as a new version comes out in the future.

**Comment by krafg** [comment]
1.20.3/1.20.4

**Comment by jpenilla** [comment]
https://github.com/jpenilla/TabTPS/commit/e21760028da61aa8bac7741057dff3c6cddedc7c

**Comment by Themis3000** [comment]
Thank you for updating and linking to the commit! I grabbed the snapshot version compiled by github actions & it seems to be working well so far.
